name: arhcoder
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get:
  flutter_svg:
  auto_size_text:
  url_launcher:

dependency_overrides:
  intl: ^0.17.0-nullsafety.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/arhcoder.png
    - assets/images/prueba.png
    - assets/icons/software.svg
    - assets/icons/design.svg
    - assets/icons/music.svg
    - assets/icons/audiovisual.svg
    - assets/icons/instagram.svg
    - assets/icons/youtube.svg
    - assets/icons/twitter.svg
    - assets/icons/github.svg
    - assets/icons/messenger.svg
    - assets/icons/gmail.svg
  fonts:
    - family: Gotham Book
      fonts:
        - asset: assets/fonts/Gotham-Book.ttf
    - family: Gotham Bold
      fonts:
        - asset: assets/fonts/Gotham-Bold.ttf
    - family: Gotham Medium
      fonts:
        - asset: assets/fonts/Gotham-Medium.ttf

flutter_intl:
  enabled: true